create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/post_margin_r[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_half_period_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_half_period_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_half_period_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_half_period_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_half_period_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_half_period_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_half_period_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_half_period_r[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 31 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[15]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[16]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[17]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[18]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[19]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[20]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[21]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[22]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[23]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[24]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[25]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[26]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[27]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[28]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[29]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/din_r[30]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repeat_counter[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/repetition_r[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/margin_counter[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/miso_width_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/miso_width_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/miso_width_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/miso_width_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/miso_width_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/miso_width_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/miso_width_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/miso_width_r[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_width_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_width_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_width_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_width_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_width_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_width_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_width_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_width_r[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 9 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_counter[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_delay_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_delay_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_delay_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_delay_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_delay_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_delay_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_delay_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_delay_r[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[15]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[16]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[17]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[18]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[19]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[20]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[21]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[22]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[23]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[24]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[25]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[26]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[27]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[28]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[29]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[30]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_dout_r[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[15]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[16]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[17]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[18]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[19]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[20]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[21]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[22]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[23]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[24]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[25]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[26]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[27]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[28]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[29]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[30]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_din_r[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[15]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[16]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[17]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[18]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[19]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[20]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[21]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[22]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[23]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[24]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[25]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[26]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[27]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[28]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[29]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[30]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/data_addr_r[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[15]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[16]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[17]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[18]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[19]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[20]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[21]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[22]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[23]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[24]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[25]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[26]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[27]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[28]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[29]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[30]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_addr_r[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 8 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/data_delay_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/data_delay_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/data_delay_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/data_delay_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/data_delay_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/data_delay_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/data_delay_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/data_delay_r[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[3]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[4]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[5]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[6]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[7]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[8]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[9]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[10]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[11]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[12]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[13]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[14]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[15]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[16]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[17]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[18]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[19]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[20]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[21]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[22]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[23]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[24]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[25]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[26]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[27]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[28]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[29]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[30]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_r[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/busy_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/busy_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cpha_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cpol_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/cs_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/ctrl_we_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/dout_valid_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 4 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/ext_trig_r[0]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/ext_trig_r[1]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/ext_trig_r[2]} {design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/ext_trig_r[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/kick_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/kick_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/mosi_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/spi_controller_i/sclk_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/SPI_CS_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/SPI_MISO_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/SPI_MOSI_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/SPI_SCLK_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/ppla_spi_repeater_0/inst/ppla_spi_repeater_int_i/repeater_i/target_kick_r]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
