set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports SPI_SCLK_0]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports SPI_MISO_0]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports SPI_MOSI_0]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports SPI_CS_0]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports EXT_TRIG_0]
